//! Add build tag safe output tool

use ado_aw_derive::SanitizeConfig;
use log::{debug, info};
use percent_encoding::utf8_percent_encode;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use super::PATH_SEGMENT;
use crate::safe_outputs::{ExecutionContext, ExecutionResult, Executor, Validate};
use crate::sanitize::{SanitizeContent, sanitize_config};
use crate::tool_result;
use anyhow::{Context, ensure};

// ── Stage 1: Params (agent-provided) ──────────────────────────────────────

/// Parameters for adding a tag to an Azure DevOps build
#[derive(Deserialize, JsonSchema)]
pub struct AddBuildTagParams {
    /// Build ID to tag (must be positive)
    pub build_id: i32,
    /// Tag string (1-100 chars, alphanumeric + dashes only)
    pub tag: String,
}

impl Validate for AddBuildTagParams {
    fn validate(&self) -> anyhow::Result<()> {
        ensure!(self.build_id > 0, "build_id must be positive");
        ensure!(!self.tag.is_empty(), "tag must not be empty");
        ensure!(self.tag.len() <= 100, "tag must be at most 100 characters");
        ensure!(
            self.tag
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b == b'-'),
            "tag must contain only alphanumeric characters and dashes"
        );
        Ok(())
    }
}

// ── Stage 1: Result (generated by macro) ──────────────────────────────────

tool_result! {
    name = "add-build-tag",
    write = true,
    params = AddBuildTagParams,
    /// Result of adding a tag to a build
    pub struct AddBuildTagResult {
        build_id: i32,
        tag: String,
    }
}

// ── Stage 3: Sanitization ─────────────────────────────────────────────────

impl SanitizeContent for AddBuildTagResult {
    fn sanitize_content_fields(&mut self) {
        self.tag = sanitize_config(&self.tag);
    }
}

// ── Stage 3: Configuration (from front matter) ────────────────────────────

/// Configuration for the add-build-tag tool
/// Example front matter:
/// ```yaml
/// safe-outputs:
///   add-build-tag:
///     allowed-tags:
///       - verified
///       - release-candidate
///     tag-prefix: "agent-"
///     allow-any-build: false
/// ```
#[derive(Debug, Clone, Default, SanitizeConfig, Serialize, Deserialize)]
pub struct AddBuildTagConfig {
    /// Restrict which tags can be applied. Empty means any tag is allowed.
    /// Supports simple wildcard patterns: entries ending with `*` match by prefix.
    #[serde(default, rename = "allowed-tags")]
    pub allowed_tags: Vec<String>,

    /// Prefix prepended to all tags before applying
    #[serde(default, rename = "tag-prefix")]
    pub tag_prefix: Option<String>,

    /// Whether the agent may tag any build. When false (default), only the
    /// current pipeline build (BUILD_BUILDID) may be tagged.
    #[serde(default, rename = "allow-any-build")]
    pub allow_any_build: bool,
}

// ── Stage 3: Execution ────────────────────────────────────────────────────

#[async_trait::async_trait]
impl Executor for AddBuildTagResult {
    fn dry_run_summary(&self) -> String {
        format!("add tag '{}' to build #{}", self.tag, self.build_id)
    }

    async fn execute_impl(&self, ctx: &ExecutionContext) -> anyhow::Result<ExecutionResult> {
        info!("Adding tag '{}' to build #{}", self.tag, self.build_id);
        debug!(
            "add-build-tag: build_id={}, tag='{}'",
            self.build_id, self.tag
        );

        // 1. Extract required context
        let org_url = ctx
            .ado_org_url
            .as_ref()
            .context("AZURE_DEVOPS_ORG_URL not set")?;
        let project = ctx
            .ado_project
            .as_ref()
            .context("SYSTEM_TEAMPROJECT not set")?;
        let token = ctx
            .access_token
            .as_ref()
            .context("No access token available")?;
        debug!("ADO org: {}, project: {}", org_url, project);

        // 2. Get tool-specific configuration
        let config: AddBuildTagConfig = ctx.get_tool_config("add-build-tag");
        debug!("Config: {:?}", config);

        // 2b. Scope check: by default only the current build can be tagged.
        // Compare in u64 space so that ADO build IDs larger than i32::MAX are
        // still enforced (the agent-supplied i32 simply cannot match such
        // values, which is the desired behavior).
        if !config.allow_any_build
            && let Some(current_id) = ctx.build_id
        {
            // self.build_id is validated > 0, so the cast to u64 is exact;
            // values that don't fit in i32 simply cannot match current_id.
            if self.build_id as u64 != current_id {
                return Ok(ExecutionResult::failure(format!(
                    "Build #{} cannot be tagged: only the current build (#{}) is \
                     allowed unless 'allow-any-build: true' is configured",
                    self.build_id, current_id
                )));
            }
        }
        // If build_id is not set (e.g. local execution), allow any build

        // 3. Apply tag prefix if configured
        let final_tag = match &config.tag_prefix {
            Some(prefix) => format!("{}{}", prefix, self.tag),
            None => self.tag.clone(),
        };
        debug!("Final tag (after prefix): {}", final_tag);

        // 4. Validate against allowed tags (if non-empty)
        if !config.allowed_tags.is_empty() {
            let allowed = config
                .allowed_tags
                .iter()
                .any(|pattern| super::tag_matches_pattern(&final_tag, pattern));
            if !allowed {
                return Ok(ExecutionResult::failure(format!(
                    "Tag '{}' is not in the allowed tags list",
                    final_tag
                )));
            }
        }

        // 5. Build the API URL
        let url = format!(
            "{}/{}/_apis/build/builds/{}/tags/{}?api-version=7.1",
            org_url.trim_end_matches('/'),
            utf8_percent_encode(project, PATH_SEGMENT),
            self.build_id,
            utf8_percent_encode(&final_tag, PATH_SEGMENT),
        );
        debug!("API URL: {}", url);

        // 6. PUT request (empty body)
        let client = reqwest::Client::new();
        info!(
            "Sending PUT to add tag '{}' to build #{}",
            final_tag, self.build_id
        );
        let response = client
            .put(&url)
            .basic_auth("", Some(token))
            .header(reqwest::header::CONTENT_LENGTH, "0")
            .body(Vec::<u8>::new())
            .send()
            .await
            .context("Failed to send request")?;

        if response.status().is_success() {
            info!("Tag '{}' added to build #{}", final_tag, self.build_id);

            Ok(ExecutionResult::success_with_data(
                format!("Added tag '{}' to build #{}", final_tag, self.build_id),
                serde_json::json!({
                    "build_id": self.build_id,
                    "tag": final_tag,
                    "project": project,
                }),
            ))
        } else {
            let status = response.status();
            let error_body = response
                .text()
                .await
                .unwrap_or_else(|_| "Unknown error".to_string());

            Ok(ExecutionResult::failure(format!(
                "Failed to add tag (HTTP {}): {}",
                status, error_body
            )))
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_execute_sends_explicit_empty_put_body() {
        use wiremock::matchers::{method, path, query_param};
        use wiremock::{Mock, MockServer, ResponseTemplate};

        let server = MockServer::start().await;
        Mock::given(method("PUT"))
            .and(path("/AgentPlayground/_apis/build/builds/42/tags/verified"))
            .and(query_param("api-version", "7.1"))
            .respond_with(ResponseTemplate::new(200))
            .mount(&server)
            .await;

        let result = AddBuildTagResult {
            name: "add-build-tag".to_string(),
            build_id: 42,
            tag: "verified".to_string(),
        };
        let mut ctx = ExecutionContext::from_env_lookup(|_| None);
        ctx.ado_org_url = Some(server.uri());
        ctx.ado_project = Some("AgentPlayground".to_string());
        ctx.access_token = Some("token".to_string());
        ctx.build_id = Some(42);

        let execution = result.execute_impl(&ctx).await.unwrap();
        assert!(
            execution.success,
            "unexpected failure: {}",
            execution.message
        );

        let requests = server
            .received_requests()
            .await
            .expect("wiremock request history should be available");
        assert_eq!(requests.len(), 1);
        assert_eq!(requests[0].body, Vec::<u8>::new());
        assert_eq!(
            requests[0]
                .headers
                .get(reqwest::header::CONTENT_LENGTH)
                .and_then(|value| value.to_str().ok()),
            Some("0")
        );
    }

    #[test]
    fn test_params_deserializes() {
        let json = r#"{"build_id": 42, "tag": "verified"}"#;
        let params: AddBuildTagParams = serde_json::from_str(json).unwrap();
        assert_eq!(params.build_id, 42);
        assert_eq!(params.tag, "verified");
    }

    #[test]
    fn test_params_converts_to_result() {
        let params = AddBuildTagParams {
            build_id: 42,
            tag: "release-candidate".to_string(),
        };
        let result: AddBuildTagResult = params.try_into().unwrap();
        assert_eq!(result.name, "add-build-tag");
        assert_eq!(result.build_id, 42);
        assert_eq!(result.tag, "release-candidate");
    }

    #[test]
    fn test_validation_rejects_zero_build_id() {
        let params = AddBuildTagParams {
            build_id: 0,
            tag: "verified".to_string(),
        };
        let err = <AddBuildTagParams as TryInto<AddBuildTagResult>>::try_into(params).unwrap_err();
        assert!(
            err.to_string().contains("build_id must be positive"),
            "unexpected error: {}",
            err
        );
    }

    #[test]
    fn test_validation_rejects_empty_tag() {
        let params = AddBuildTagParams {
            build_id: 42,
            tag: "".to_string(),
        };
        let err = <AddBuildTagParams as TryInto<AddBuildTagResult>>::try_into(params).unwrap_err();
        assert!(
            err.to_string().contains("tag must not be empty"),
            "unexpected error: {}",
            err
        );
    }

    #[test]
    fn test_validation_rejects_invalid_tag_chars() {
        let params = AddBuildTagParams {
            build_id: 42,
            tag: "invalid tag!".to_string(),
        };
        let err = <AddBuildTagParams as TryInto<AddBuildTagResult>>::try_into(params).unwrap_err();
        assert!(
            err.to_string().contains("alphanumeric"),
            "unexpected error: {}",
            err
        );
    }

    #[test]
    fn test_result_serializes_correctly() {
        let params = AddBuildTagParams {
            build_id: 42,
            tag: "verified".to_string(),
        };
        let result: AddBuildTagResult = params.try_into().unwrap();
        let json = serde_json::to_string(&result).unwrap();
        assert!(json.contains(r#""name":"add-build-tag""#));
        assert!(json.contains(r#""build_id":42"#));
        assert!(json.contains(r#""tag":"verified""#));
    }

    #[test]
    fn test_config_defaults() {
        let config = AddBuildTagConfig::default();
        assert!(config.allowed_tags.is_empty());
        assert!(config.tag_prefix.is_none());
    }

    #[test]
    fn test_config_deserializes_from_yaml() {
        let yaml = r#"
allowed-tags:
  - verified
  - release-candidate
tag-prefix: "agent-"
"#;
        let config: AddBuildTagConfig = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(config.allowed_tags, vec!["verified", "release-candidate"]);
        assert_eq!(config.tag_prefix, Some("agent-".to_string()));
    }
}
